logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
Spring:
  rabbitmq:
    host: 192.168.32.3 #rabbitMQ的ip地址
    port: 5672 #端口
    username: itcast
    password: 123321
    virtual-host: /
    listener:
      simple:
        prefetch: 1
